comments, strings, etc.

diff --git a/dotm b/dotm
--- a/dotm
+++ b/dotm
@@ -1,17 +1,54 @@
 #!/bin/bash
 # Little dotfiles manager
 
-## Variables
-# Replacing $HOME with another location for the testing stage
-TESTHOME=$HOME/tmp
+#------------------------------------------------------------------------------
+# Global variables
+#------------------------------------------------------------------------------
 
+## User variables
+# Replace $HOME with another location for tests
+BACKUPDIR=backups
+CONFIGDIR=$HOME
+CONFIGFILE="dotm.rc"
+
+## Variables for version and help printing
 DATE="Feburary 23rd 2013"
 VERSION="0.3"
 
+VERSIONSTRING="dotm, version $VERSION ($DATE)
+
+This program is free software. It comes WITHOUT ANY WARRANTY, to
+the extent permitted by applicable law. You can redistribute it
+and/or modify it under the terms of the Do What The Fuck You Want
+To Public License, Version 2, as published by Sam Hocevar. See
+http://sam.zoy.org/wtfpl/COPYING for more details.
+
+Written by Harenome Ranaivoarivony Razanajato"
+
+HELPSTRING="Usage: $0 [OPTIONS]... [FILES]...
+
+Options:
+    --backup
+        enable backups
+    --force-overwrite
+        force overwriting of links, files and dir
+    --help
+        print this help
+    --overwrite-link
+        overwrite links
+    --overwrite-file
+        overwrite files
+    --overwrite-dir
+        overwrite directories
+    --verbose
+        enable verbose mode
+    --version
+        print the version"
+
+## Vital variables for the script
 # Dirty (and hopefully, temporary) way to get the full path
 DIRNAME="$(pwd)$([[ $(dirname $0) = "." ]] || echo "/$(dirname $0)")"
 
-CONFIGFILE="dotm.rc"
 DOBACKUPS=true
 FORCEOVERWRITE=false
 OVERWRITELINK=false
@@ -22,47 +59,31 @@ WRONGARGUMENT=false
 UNKNOWNFILE=false
 FILELIST=( )
 
-HELPSTRING="Usage: ./dotm [OPTIONS]\n\n
-\t--backup\n
-\t\tenable backups\n
-\t--force-overwrite\n
-\t\tforce overwriting of links, files and dir\n
-\t--help\n
-\t\tprint this help\n
-\t--overwrite-link\n
-\t\toverwrite links\n
-\t--overwrite-file\n
-\t\toverwrite files\n
-\t--overwrite-dir\n
-\t\toverwrite directories\n
-\t--verbose\n
-\t\tenable verbose mode\n
-\t--version\n
-\t\tprint the version\n
-"
+#------------------------------------------------------------------------------
+# Functions
+#------------------------------------------------------------------------------
 
-## Functions
 function version
 {
-    echo "dotm, version $VERSION ($DATE)"
+    echo -e "$VERSIONSTRING"
 }
 
 function printhelp
 {
     # TODO: complete the help
 
-    echo -en $HELPSTRING
+    echo -e "$HELPSTRING"
 }
 
 function backup
 {
-    cp -r "$1" backups/
+    cp -r "$1" $BACKUPDIR/
 }
 
 # Not tested yet
 function restore
 {
-    cp -rf "backups/$1" $TESTHOME/
+    cp -rf "backups/$1" $CONFIGDIR/
 }
 
 function createlink
@@ -72,11 +93,11 @@ function createlink
     # ln has a backup feature, however it is limited
     # (the backup is done in the same directory)
     local TARGET="$DIRNAME/$2"
-    local DESTINATION="$TESTHOME/$1"
+    local DESTINATION="$CONFIGDIR/$1"
 
     if [[ -e "$DESTINATION" ]]; then
         if [[ -h "$DESTINATION" ]]; then
-            if $VERBOSE; then echo "$DESTINATION is a link to $(readlink $DESTINATION)."; fi
+            if $VERBOSE; then echo "$DESTINATION is a link to $(readlink $DESTINATION)." 1>&2; fi
             if $OVERWRITELINK || $FORCEOVERWRITE; then
                 if $VERBOSE; then echo "Overwriting the link (New target: $TARGET)."; fi
                 ln -sf "$TARGET" "$DESTINATION"
@@ -84,7 +105,7 @@ function createlink
                 echo "Ignoring."
             fi
         elif [[ -f "$DESTINATION" ]]; then
-            if $VERBOSE; then echo "There already exists a file at $DESTINATION."; fi
+            if $VERBOSE; then echo "There already exists a file at $DESTINATION." 1>&2; fi
             if $DOBACKUPS; then
                 if $VERBOSE; then echo "Backuping $DESTINATION."; fi
                 backup "$DESTINATION"
@@ -94,7 +115,7 @@ function createlink
                 ln -sf "$TARGET" "$DESTINATION"
             elif $VERBOSE; then echo "Ignoring."; fi
         elif [[ -d "$DESTINATION" ]]; then
-            if $VERBOSE; then echo "$DESTINATION is a directory."; fi
+            if $VERBOSE; then echo "$DESTINATION is a directory." 1>&2; fi
             if $DOBACKUPS; then
                 if $VERBOSE; then echo "Backuping $DESTINATION."; fi
                 backup "$DESTINATION"
@@ -118,7 +139,7 @@ function checkconfigfile
 
     for FILE in $(grep -Env "#|:|^$" $CONFIGFILE | cut -d " " -f 2); do
         [[ ! -e "$FILE" ]] &&
-        echo "Error: The file $FILE doesn't exist. Please check your $CONFIGFILE file." &&
+        echo "Error: The file $FILE doesn't exist. Please check your $CONFIGFILE file." 1>&2 &&
         HASERROR=true
     done
 
@@ -128,7 +149,7 @@ function checkconfigfile
 function isinconfigfile
 {
     if ! grep "^$(echo $1):$" $CONFIGFILE > /dev/null; then
-        echo "Error: Don't know how to handle the config files for $1. Please check your $CONFIGFILE file."
+        echo "Error: Don't know how to handle the config files for $1. Please check your $CONFIGFILE file." 1>&2
         UNKNOWNFILE=true
     else
         FILELIST=( ${FILELIST[@]} $1 )
@@ -152,9 +173,12 @@ function allconfig
     done
 }
 
-## Main
+#------------------------------------------------------------------------------
+# Main
+#------------------------------------------------------------------------------
+
 checkconfigfile
-mkdir -p backups
+mkdir -p $BACKUPDIR
 
 if [[ $# -eq 0 ]]; then
     allconfig
@@ -171,7 +195,7 @@ else
                 "--force-overwrite" ) FORCEOVERWRITE=true;;
                 "--version" ) version; exit 0;;
                 "--help" ) printhelp; exit 0;;
-                * ) echo "Wrong option: $ARG"; WRONGARGUMENT=true;;
+                * ) echo "Wrong option: $ARG" 1>&2; WRONGARGUMENT=true;;
             esac
         else
             isinconfigfile $ARG
