path to directory, config check

diff --git a/dotm b/dotm
--- a/dotm
+++ b/dotm
@@ -1,20 +1,22 @@
 #!/bin/bash
 # Little dotfiles manager
 
-# Variables
+## Variables
 # Replacing $HOME with another location for the testing stage
 TESTHOME=$HOME/tmp
 
 DATE="January 28th 2013"
 VERSION="0.1"
-DIRNAME="$(dirname $0)"
+
+# Dirty (and hopefully, temporary) way to get the full path
+DIRNAME="$(pwd)$([[ $(dirname $0) = "." ]] || echo "/$(dirname $0)")"
 
 CONFIGFILE="dotm.rc"
 DOBACKUPS=true
 OVERWRITELINKS=true
-VERBOSE=false
+VERBOSE=true
 
-# Functions
+## Functions
 function version
 {
     echo "dotm, version $VERSION ($DATE)"
@@ -65,32 +67,49 @@ function createlink
     fi
 }
 
+function checkconfig
+{
+    local HASERROR=false
+
+    for LINE in $(grep -Env "#|:|^$" $CONFIGFILE | cut -d " " -f 2); do
+        [[ ! -e "$LINE" ]] &&
+        echo "Error: The file $LINE doesn't exist. Please check your dotm.rc file." &&
+        HASERROR=true
+    done
+
+    if $HASERROR; then exit 1; fi
+}
+
 function singleconfig
 {
     BEGINNING=$(grep -n "^$(echo $1):$" $CONFIGFILE | cut -d ':' -f 1)
-    for LINE in "$(awk '{ if (NR > '$BEGINNING') if (length($0) > 0) { print } else { exit } }')"; do
+    for LINE in "$(awk '{ if (NR > '$BEGINNING') if (length($0) > 0) { print } else { exit } }' $CONFIGFILE)"; do
         createlink $(echo "$LINE")
     done
 }
 
 function allconfig
 {
-    for LINE in "$(grep -Ev ":|^$" $CONFIGFILE)"; do
-        createlink $(echo "$LINE")
+    for LINE in "$(grep -Ev "#|:|^$" $CONFIGFILE)"; do
+        createlink $(echo $LINE | cut -d " " -f 1) $(echo $LINE | cut -d " " -f 2)
     done
 }
 
 function interactive
 {
+    echo ""
 }
 
-# Main
+## Main
+checkconfig
 mkdir -p backups
 
 if [[ $# -eq 0 ]]; then
-    interactive
+    #interactive
+    echo "TODO"
+    #allconfig
 else
-
+    singleconfig $1
 fi
 
 exit 0
